global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "mlflow-exporter"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: /metrics

  - job_name: "mlflow-model-serving"
    static_configs:
      - targets: ["localhost:1234"]
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
